version: "3.7"
services:
 myjenkins:
  build:
   context: .
   dockerfile:Dockerfile
  restart:unless-stopped

  ports:
   -"8081:8080"
  volumes:
   -/var/jenkins:/var/jenkins_home
  container_name:myjenkins
